// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tyrell.Models;

namespace Tyrell.Migrations
{
    [DbContext(typeof(PostContext))]
    [Migration("20181220164009_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview1-35029")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Tyrell.Models.Comment", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("Postid");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("language");

                    b.Property<string>("postId");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.HasIndex("Postid");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Tyrell.Models.Post", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.Property<DateTime>("createdAt");

                    b.Property<bool>("isReply");

                    b.Property<bool>("isVisible");

                    b.Property<string>("language");

                    b.Property<int>("numOfRepost");

                    b.Property<string>("replyUser");

                    b.Property<string>("userId");

                    b.HasKey("id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Tyrell.Models.Comment", b =>
                {
                    b.HasOne("Tyrell.Models.Post")
                        .WithMany("comments")
                        .HasForeignKey("Postid");
                });
#pragma warning restore 612, 618
        }
    }
}
